parameterize class
k8-proxy/k8-vmware pull request #24
Opened 2021-01-14 15:42 UTC by naderaly

2021-01-15 01:34 UTC, dinis-cruz-gw requested changes

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +from pathlib import Path, PurePath
use file methods from OSBot_Utils

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +	def __init__(self,rm_note,dont_rm_note,expire_days_no):
what is `rm_note` ? 

use longer variable names (make it easier to read and understand)

(same for other variables)

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +
add `self.sdk = sdk()` here

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		if not self.expire_days_no.isdigit():
refactor param validation into separate method

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		vms_o = sdk.get_objects_Virtual_Machines()
use `vms` as variable name

use this method to get the vms https://github.com/k8-proxy/k8-vmware/blob/main/k8_vmware/vsphere/Sdk.py#L315

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		for vm_o in vms_o:
use `vm` as variable name

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    create_date=vm_o.config.createDate
align spacing , it should look like this

![image](https://user-images.githubusercontent.com/57914593/104668512-22163880-56d0-11eb-9f0e-a318c050f7dc.png)

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    vm = VM(vm_o)
don't need to do this if https://github.com/k8-proxy/k8-vmware/blob/main/k8_vmware/vsphere/Sdk.py#L315 is used to get the vms

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    (create_date < (now - timedelta(days=self.expire_days_no)) and (not self.dont_rm_note or self.dont_rm_note.lower() not in notes.lower())):
refactor all the code above into a method called something like "vms_to_delete"

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    	if state == 'poweredOn':
no need to check this here, because the task().delete() also checks it https://github.com/k8-proxy/k8-vmware/blob/main/k8_vmware/vsphere/VM_Task.py#L16

![image](https://user-images.githubusercontent.com/57914593/104668847-cbf5c500-56d0-11eb-9a9b-61a9e396fae7.png)

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    	removed_VMs.append(info["Name"])
refactor delete actions into separate method called 'remove_vms' which takes a list of vms to delete as parms

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +		    print("No VM was removed!")
put this in a method call something like 'run' which uses the other methods mentioned above

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +class AutoDeleteEsxiJob:
rename to `Delete_Old_VMs'

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +def main():
create test class that tests each function separately

main should only be something like Delete_Old_VMs().run()

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +	load_dotenv(dotenv_path=env_path)
loading of env variables should be in a method inside Delete_Old_VMs clas

2021-01-15 01:34 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +	load_dotenv(dotenv_path=env_path)
look at https://github.com/k8-proxy/k8-vmware/blob/main/k8_vmware/Config.py#L4 for reference

2021-01-22 12:00 UTC, GINAGC commented
@naderaly review the comments from Dinis and reply using the following:

:+1: means change made
:eyes: means you read it and understood the comment/request
:thumbsdown: means that you didn't implement the change (which is OK, nothing wrong with that, BUT, please add a note to it with some rational)

Once that is ready for review again, please let me know.

2021-01-26 14:56 UTC, closed without merging