auto/manual start/stop vm scripts
k8-proxy/k8-vmware pull request #25
Opened 2021-01-17 08:20 UTC by belwase

- script to start/stop vm ( manual or scheduled )
- refactored based on dinis's comments

2021-01-18 11:34 UTC, belwase commented
@DinisCruz  Please don't review this yet. I need to integrate Naider's code to same class

2021-01-18 12:02 UTC, dinis-cruz-gw requested changes

2021-01-18 12:02 UTC, dinis-cruz-gw commented on scripts/vm_utils.py
> +                time.sleep(30)
this is weird, does this mean that this process will be running for a large amount of time?

methods should always execute as fast as possible

2021-01-18 12:02 UTC, dinis-cruz-gw commented on tests/unit/scripts/test_vm_utils.py
> +        pass
the last of tests here shows me that you are not using tests to develop your code (which you should)

**desired use-case:** 
as a reviewer, I should be able to read your tests and understand how the code is working and what are your assumptions and intentions

2021-01-18 12:09 UTC, naderaly commented on scripts/esxi-cleanup.py
> +        vms                     = self.sdk.get_objects_Virtual_Machines()
Hello @dinis-cruz-gw , the thing is 'sdk.vms()' doesn't return createDate which is needed to calculate each vm age.
Please correct me if I'm wrong

2021-01-22 11:30 UTC, dinis-cruz-gw commented on scripts/esxi-cleanup.py
> +        vms                     = self.sdk.get_objects_Virtual_Machines()
if it doesn't then add that method to it (since the code is in this repo :) )

2021-01-22 12:00 UTC, GINAGC commented
@belwase review the comments from Dinis and reply using the following:

:+1: means change made
:eyes: means you read it and understood the comment/request
:thumbsdown: means that you didn't implement the change (which is OK, nothing wrong with that, BUT, please add a note to it with some rational)

Once that is ready for review again, please let me know.

2021-01-25 03:14 UTC, belwase commented on scripts/esxi-cleanup.py
> +    def __validate_days_type(self):
renamed to "validate_days_type"

2021-01-25 03:14 UTC, belwase commented on scripts/esxi-cleanup.py
> +            sys.exit(1)
added return bool

2021-01-25 03:14 UTC, belwase commented on scripts/esxi-cleanup.py
> +                            not self.dont_delete_note or self.dont_delete_note.lower() not in notes.lower())):
refactored

2021-01-25 03:15 UTC, belwase commented on scripts/vm_utils.py
> +        self.not_shutdown_tag = environ.get("not_shutdown_tag", None)
alinged

2021-01-25 03:16 UTC, belwase commented on scripts/vm_utils.py
> +class VMUtils:
the script class has been renamed to "Esxi_Power" and filename to "esxi_power.py"

2021-01-25 03:18 UTC, belwase commented on scripts/vm_utils.py
> +            altered = self.do_action(self.mode_tag, vm)
self.do_action was added thinking we'll add more action on future

2021-01-25 03:18 UTC, belwase commented on scripts/vm_utils.py
> +    def do_action(self, action, vm):
checks are added . it will run only specific actions allowed by class

2021-01-25 03:27 UTC, belwase commented on scripts/vm_utils.py
> +    def format_expected_date(self, dt):
Added to Utils class

2021-01-25 03:28 UTC, belwase commented on scripts/vm_utils.py
> +                time.sleep(30)
this code will run when a user runs a script to do some actions at a scheduled time. so it needs to wait for sometime.

2021-01-25 03:39 UTC, belwase commented on tests/unit/scripts/test_vm_utils.py
> +        pass
Added tests

2021-01-25 03:42 UTC, belwase commented
Hi @GINAGC  @DinisCruz  updates are made as per discussions.

2021-01-26 14:15 UTC, dinis-cruz-gw approved these changes
Looks good , thanks for the changes

2021-01-26 14:15 UTC, merged